# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@5

jobs:
  test:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install coverage
      - run:
          name: Run tests
          command: python -m unittest discover
      - run:
          name: Run coverage
          command: coverage run -m unittest discover && coverage xml
      - codecov/upload

workflows:
  test-workflow:
    jobs:
      - test
